import { StyleSheet } from 'react-native';

import { colors } from '@/theme/colors';
import { spacing } from '@/theme/spacing';

export const accountStyles = StyleSheet.create({
  content: {
    paddingHorizontal: 0,
    paddingBottom: 0,
    gap: 0,
    backgroundColor: colors.surface,
  },
  page: {
    gap: spacing.lg,
    padding: spacing.lg,
  },
  title: {
    color: colors.text,
    fontSize: 34,
    fontWeight: '900',
  },
  subtitle: {
    color: colors.textMuted,
    fontSize: 15,
  },
  signedOutCard: {
    gap: spacing.lg,
    margin: spacing.lg,
    borderColor: colors.border,
    borderWidth: 1,
    borderRadius: 22,
    backgroundColor: colors.surface,
    padding: spacing.xl,
  },
  profileCard: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.md,
    borderColor: colors.border,
    borderWidth: 1,
    borderRadius: 22,
    backgroundColor: colors.surface,
    padding: spacing.lg,
    shadowColor: colors.text,
    shadowOpacity: 0.08,
    shadowRadius: 10,
    elevation: 2,
  },
  avatar: {
    width: 58,
    height: 58,
    borderRadius: 29,
    backgroundColor: '#dceaff',
    alignItems: 'center',
    justifyContent: 'center',
  },
  avatarText: {
    color: colors.primary,
    fontSize: 24,
    fontWeight: '900',
  },
  profileText: {
    flex: 1,
  },
  profileName: {
    color: colors.text,
    fontSize: 21,
    fontWeight: '900',
  },
  profileEmail: {
    color: colors.textMuted,
  },
  menuCard: {
    borderColor: colors.border,
    borderWidth: 1,
    borderRadius: 22,
    backgroundColor: colors.surface,
    padding: spacing.md,
    shadowColor: colors.text,
    shadowOpacity: 0.06,
    shadowRadius: 10,
    elevation: 2,
  },
  menuItem: {
    minHeight: 54,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderRadius: 14,
    paddingHorizontal: spacing.lg,
  },
  menuItemActive: {
    backgroundColor: '#eaf3ff',
    borderLeftColor: colors.primary,
    borderLeftWidth: 4,
  },
  menuText: {
    color: colors.textMuted,
    fontWeight: '900',
  },
  menuTextActive: {
    color: colors.primary,
  },
  chevron: {
    color: colors.label,
    fontSize: 28,
  },
  chevronActive: {
    color: colors.primary,
  },
  menuDivider: {
    height: 1,
    backgroundColor: colors.border,
    marginVertical: spacing.sm,
  },
  logoutText: {
    color: colors.danger,
    fontWeight: '900',
  },
  detailsCard: {
    gap: spacing.xl,
    borderColor: colors.border,
    borderWidth: 1,
    borderRadius: 24,
    backgroundColor: colors.surface,
    padding: spacing.lg,
  },
  detailsTitle: {
    color: colors.text,
    fontSize: 24,
    fontWeight: '900',
  },
  profileHero: {
    gap: spacing.lg,
    borderColor: colors.border,
    borderWidth: 1,
    borderRadius: 20,
    backgroundColor: colors.surfaceMuted,
    padding: spacing.lg,
  },
  largeAvatar: {
    width: 96,
    height: 96,
    borderRadius: 48,
    backgroundColor: '#d7e7ff',
    alignItems: 'center',
    justifyContent: 'center',
  },
  largeAvatarText: {
    color: colors.primary,
    fontSize: 38,
    fontWeight: '900',
  },
  heroText: {
    gap: spacing.xs,
  },
  profileLabel: {
    color: colors.label,
    fontSize: 12,
    fontWeight: '900',
    letterSpacing: 4,
  },
  greeting: {
    color: colors.text,
    fontSize: 26,
    fontWeight: '900',
  },
  formGrid: {
    gap: spacing.lg,
  },
  fieldGroup: {
    gap: spacing.sm,
  },
  fieldLabel: {
    color: colors.text,
    fontWeight: '900',
  },
  input: {
    minHeight: 56,
    borderColor: colors.border,
    borderWidth: 1,
    borderRadius: 12,
    backgroundColor: colors.surfaceMuted,
    color: colors.text,
    paddingHorizontal: spacing.lg,
    fontSize: 16,
  },
  helper: {
    color: colors.label,
    fontSize: 12,
    fontWeight: '900',
    letterSpacing: 1,
  },
  emptyText: {
    color: colors.textMuted,
    textAlign: 'center',
  },
  stack: {
    gap: spacing.md,
  },
  infoCard: {
    gap: spacing.xs,
    borderColor: colors.border,
    borderWidth: 1,
    borderRadius: 16,
    backgroundColor: colors.surfaceMuted,
    padding: spacing.lg,
  },
  rowBetween: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: spacing.sm,
  },
  cardHeading: {
    color: colors.text,
    fontSize: 16,
    fontWeight: '900',
  },
  cardBody: {
    color: colors.textMuted,
  },
  cardBodyStrong: {
    color: colors.text,
    fontWeight: '700',
  },
  badge: {
    color: colors.primary,
    fontWeight: '900',
  },
  headerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
  },
  backButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
    borderColor: colors.border,
    borderWidth: 1,
    backgroundColor: colors.surface,
  },
  backButtonText: {
    color: colors.primary,
    fontSize: 28,
    fontWeight: '700',
    lineHeight: 28,
  },
  sectionIntro: {
    color: colors.textMuted,
    fontSize: 15,
    lineHeight: 22,
  },
  centerCard: {
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing.md,
    minHeight: 320,
  },
  centerIcon: {
    width: 76,
    height: 76,
    borderRadius: 38,
    backgroundColor: colors.surfaceMuted,
    alignItems: 'center',
    justifyContent: 'center',
  },
  centerIconText: {
    color: colors.label,
    fontSize: 30,
  },
  centerTitle: {
    color: colors.text,
    fontSize: 18,
    fontWeight: '900',
    textAlign: 'center',
  },
  centerBody: {
    color: colors.textMuted,
    fontSize: 15,
    lineHeight: 24,
    textAlign: 'center',
  },
  actionRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: spacing.md,
  },
  primaryAction: {
    minHeight: 52,
    minWidth: 170,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 16,
    backgroundColor: '#ff7a00',
    paddingHorizontal: spacing.lg,
  },
  primaryActionText: {
    color: colors.surface,
    fontSize: 16,
    fontWeight: '900',
  },
  linkAction: {
    minHeight: 44,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: spacing.sm,
  },
  linkActionText: {
    color: colors.primary,
    fontSize: 16,
    fontWeight: '900',
  },
  outlineButton: {
    minHeight: 52,
    alignItems: 'center',
    justifyContent: 'center',
    borderColor: colors.border,
    borderWidth: 1,
    borderRadius: 16,
    backgroundColor: colors.surface,
    paddingHorizontal: spacing.lg,
    alignSelf: 'flex-start',
  },
  outlineButtonText: {
    color: colors.text,
    fontSize: 16,
    fontWeight: '900',
  },
  divider: {
    height: 1,
    backgroundColor: colors.border,
  },
  settingsRow: {
    minHeight: 84,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: spacing.md,
  },
  switchTrack: {
    width: 54,
    height: 32,
    borderRadius: 16,
    backgroundColor: colors.primary,
    padding: 4,
    justifyContent: 'center',
  },
  switchTrackOff: {
    backgroundColor: '#c7d4ea',
  },
  switchThumb: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: colors.surface,
    alignSelf: 'flex-end',
  },
  switchThumbOff: {
    alignSelf: 'flex-start',
  },
});
