# SonarCloud Automatic Analysis configuration
sonar.projectName=greenovate-mobile
sonar.sources=shelf-awareness,nexus
sonar.exclusions=**/node_modules/**,**/build/**,**/.gradle/**,**/coverage/**,**/*.xml,**/*.plist,**/*.xcprivacy
sonar.issue.ignore.multicriteria=e1
sonar.issue.ignore.multicriteria.e1.ruleKey=xml:S5604
sonar.issue.ignore.multicriteria.e1.resourceKey=**/*.xml
