# .sonarcloud.properties
# This file configures the SonarCloud Automatic Analysis.
# We are excluding everything here to resolve the conflict with our CI-based analysis
# without needing to change the SonarCloud UI settings or the pipeline code.

sonar.sources=
sonar.tests=
sonar.exclusions=**/*
